### PR TITLE
added jumpthrow

### PR DESCRIPTION
**Pull request by ruddan**

### CODE REVIEW

**Review by bombsimon — CHANGES_REQUESTED** [review]
Thanks!

This overrides a previously bound key (without replacing it):

```txt
bind "v" "give weapon_hegrenade;give weapon_flashbang;give weapon_smokegrenade;give weapon_incgrenade;give weapon_molotov;give weapon_decoy"
```

Would you mind re-binding the above to `h` (since it's used more seldom)?

Also, would you mind splitting the aliases up for readability? Something like

```txt
alias "+jumpthrow" "+jump;-attack"
alias "-jumpthrow" "-jump"
bind v "+jumpthrow"
```

**Comment by bombsimon** [comment]
Btw, do you know if the aliases can be defined after the bindings? If so, do you mind putting the bind-command between the other commands? If not, maybe add the aliases first so they can be referenced in the correct section and move the bind to the rest of the binds.

You absolutely doesn't have to do this, I'll do it after merging your changes otherwise. :)

**Comment by bombsimon** [comment]
Also, what exactly does `-[bind]` do? Why is `-jumpthrow` aliased but never used? Is it the bind for when a key is released so when you release the jump throw bind you'll stop attacking? Seems weird though since you don't have to bind `-jump` to stop jumping after pressing space. :D

**Comment by bombsimon** [comment]
Also, not important for this commit but you should start using [imperative mood](https://chris.beams.io/posts/git-commit/#imperative) and [capitalize subject](https://chris.beams.io/posts/git-commit/#capitalize) in your commit messages. 🚀

**Comment by ruddan** [comment]
"Also, what exactly does -[bind] do? Why is -jumpthrow aliased but never used?"
It's needed so that you can jump again after the jumpthrow, when you release your jumpthrow-bind the "-[bind]" is executed.

**Comment by ruddan** [comment]
> Btw, do you know if the aliases can be defined after the bindings? If so, do you mind putting the bind-command between the other commands? If not, maybe add the aliases first so they can be referenced in the correct section and move the bind to the rest of the binds.
> 
> You absolutely doesn't have to do this, I'll do it after merging your changes otherwise. :)

I have not tried but I think it should work.

**Review by bombsimon — APPROVED** [review]
I meant to re-bind the old `v` and use `v` for jumpthrow but this will do, I'll fix! Thanks!

**Pull request merged**
